name: quest_signin_dashboard
description: "A new Quest."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  get_it: ^7.7.0
  path_provider: ^2.1.3
  uuid: ^4.4.2
  flutter_svg: ^2.0.10+1
  flutter_chat_bubble: ^2.0.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/vectors/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
